apiVersion: v1
kind: ConfigMap
metadata:
 name: wendyvallejo24-config
 labels:
   app: postgres
data:
 DEV_SECRET_KEY: soy-wendy-xd
 DEV_DATABASE: glbdqgmj
 DEV_USER: glbdqgmj
 DEV_PASSWORD: ebLhfes2S_PIi-K8EVWT8q9hJ3f6B3tR
 DEV_HOST: mahmud.db.elephantsql.com
 DEV_PORT: "5432"
 
 PROD_SECRET_KEY: soy-wendy-xd
 PROD_DATABASE: glbdqgmj
 PROD_USER: glbdqgmj
 PROD_PASSWORD: ebLhfes2S_PIi-K8EVWT8q9hJ3f6B3tR
 PROD_HOST: mahmud.db.elephantsql.com
 PROD_PORT: "5432"
