apiVersion: v1
kind: ConfigMap
metadata:
 name: wendyvallejo24-config
 labels:
   app: postgres
data:
 DEV_SECRET_KEY: MY_DEV_SECRET_KEY
 DEV_DATABASE: MY_DEV_DATABASE
 DEV_USER: MY_DEV_USER
 DEV_PASSWORD: MY_DEV_PASSWORD
 DEV_HOST: MY_DEV_HOST
 DEV_PORT: MY_DEV_PORT
 
 PROD_SECRET_KEY: soy-wendy-xd
 PROD_DATABASE: glbdqgmj
 PROD_USER: glbdqgmj
 PROD_PASSWORD: ebLhfes2S_PIi-K8EVWT8q9hJ3f6B3tR
 PROD_HOST: mahmud.db.elephantsql.com
 PROD_PORT: "5432"
